### PR TITLE
Store configuration in database instead of config file

### PR DESCRIPTION
**Pull request by ThumNet**
In Umbraco Cloud the config file is added to the GIT repo. This means setting the 404 on staging environment, results in a change on the .config file, which then can be pushed to the live environment. 

But in Umbraco Cloud the page IDs differ per environment, so the 404 won't work in the Live environment. This can be resolved by setting the page again on the live environment. But this is required each time the staging is pushed to live.

By storing the 404 configuration in the database the problem described above is prevented, small drawback it is required to configure the 404 page per environment.

Another way to support the cloud would be by using the [UDI](https://our.umbraco.org/documentation/reference/querying/Udi) (added in Umbraco 7.6), but that would not be supported by older Umbraco versions.

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Awesome, thanks for the pull request, does this also migrate the existing file config to db?

**Comment by ThumNet** [comment]
In the current Pull request no, it doesn't. But that can be arranged :)

What's a good approach here? Create a new pull request with all changes or create a second one?

**Comment by TimGeyssens** [comment]
Ace, whatever you think is easiest works for me :)

**Comment by ThumNet** [comment]
There you go :+1:

**Comment by TimGeyssens** [comment]
Nice, will check it out this week and then merge + release new version, thanks again for the pull request!

**Comment by ThumNet** [comment]
You're very welcome, let me know if you have any issues!

**Pull request merged**
